name: Security Checks

on:
  push:
    branches: 
      - main
      - security-pipeline
  pull_request:
    branches:
      - main
      - security-pipeline 
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays   

jobs: 
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Step 1: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Or use 18 if supported

      # Step 2: Install all dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev eslint eslint-plugin-security eslint-plugin-node

      # Step 3: Run ESLint and output JSON report
      - name: Run ESLint
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx --format json -o eslint-results.json || true

      # Optional Step 4: Upload ESLint results as an artifact
      - name: Upload ESLint Report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-results
          path: eslint-results.json
