name: Security Checks

on:
  push:
    branches:
      - main
      - security-pipeline
  pull_request:
    branches:
      - main
      - security-pipeline
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays

jobs:
  security-checks:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write  # Required for CodeQL uploads

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js for ESLint and Snyk
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install --save-dev eslint eslint-plugin-security eslint-plugin-node

      # Run ESLint and generate JSON report
      - name: Run ESLint
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx --format json -o eslint-results.json || true

      # Upload ESLint Report
      - name: Upload ESLint Report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-results
          path: eslint-results.json

      # Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      # Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: results/javascript.sarif

      # Upload CodeQL SARIF Report
      - name: Upload CodeQL SARIF Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results/javascript.sarif
          category: custom-codeql-analysis

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      # Run Snyk to check for vulnerabilities
      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --all-projects --json-file-output=snyk-results.json || true

      # Upload Snyk JSON Report
      - name: Upload Snyk JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-results
          path: snyk-results.json
