name: Security Checks

on:
   push:
    branches: 
      - main
      - security-pipeline
   pull_request:
     branches:
        - main
        - security-pipeline 
   schedule:
     - cron: '0 0 * * 0'  # Weekly on sundays   

jobs: 
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
# Static Application Security Testing (SAST) with CodeQL

 # Step 1: Set up Node.js for ES lint
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use Node.js 16.x

# Step 2: Install dependencies
      - name: Install dependencies
        run: npm install

        # Step 3: Run ESLint for code linting
      - name: Install ESLint
        run: npm install eslint eslint-plugin-security --save-dev

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --format json > eslint-results.json || true
